name: "构建shiori正式版"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建shiori正式版
    env:
      IMAGE_NAME: shiori
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 设置QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 设置Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: 登陆Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: 构建shiori镜像并推送
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          file: Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64,linux/ppc64le,linux/arm/v7,linux/arm/v6
          tags: ${{ secrets.DOCKER_USERNAME }}/shiori:latest
